name: funnews
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: any
  shimmer_animation: ^2.1.0+1
  firebase_auth: ^3.1.4
  http: ^0.13.4
  dio: ^4.0.1
  shimmer: ^2.0.0
  url_launcher: ^6.0.12
  mobx: ^2.0.0
  flutter_mobx: ^2.0.0
  get_it: ^7.2.0
  webview_flutter: ^2.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^1.12.2
  mobx_codegen: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/ 
